import { useCallback, useEffect, useRef, useState } from 'react';
import { Alert, Box, Card, CardContent, Checkbox, Chip, CircularProgress, Dialog, DialogContent, Divider, FormControl, IconButton, InputLabel, MenuItem, Select, Typography } from '@mui/material';
import ChevronLeftIcon from '@mui/icons-material/ChevronLeft';
import ChevronRightIcon from '@mui/icons-material/ChevronRight';
import DeleteOutlineIcon from '@mui/icons-material/DeleteOutlineOutlined';
import CloseIcon from '@mui/icons-material/Close';
import InsertDriveFileOutlinedIcon from '@mui/icons-material/InsertDriveFileOutlined';
import ImageOutlinedIcon from '@mui/icons-material/ImageOutlined';
import AudioFileOutlinedIcon from '@mui/icons-material/AudioFileOutlined';
import { api } from '../services/api';
import { useLayoutHeaderActions } from '../components/layout/AppLayoutContext';
import { useNavigate } from 'react-router-dom';
import { useAuthStore } from '../stores/useAuthStore';
import { useMessageStore } from '../stores/useMessageStore';

type Category = 'all' | 'document' | 'image' | 'sticker' | 'avatar' | 'character' | 'background' | 'audio' | 'table' | 'web' | 'other';
const categories: Array<[Category, string]> = [['all','全部'],['document','文档'],['image','图片'],['sticker','表情'],['audio','语音'],['table','表格'],['web','网页'],['other','其他']];
const ranges = [['all','不限'],['today','今天'],['week','一周内'],['month','一月内'],['halfYear','半年内'],['cloud-only','其余设备'],['unreferenced','未引用']] as const;
const specialCategories = new Set<string>();

function icon(category: string) { return category === 'image' ? <ImageOutlinedIcon /> : category === 'audio' ? <AudioFileOutlinedIcon /> : <InsertDriveFileOutlinedIcon />; }
function rangeStart(value: string) { const now = Date.now(); if (value === 'today') return new Date(new Date().setHours(0,0,0,0)).getTime(); if (value === 'week') return now - 7*864e5; if (value === 'month') return now - 30*864e5; if (value === 'halfYear') return now - 182*864e5; return undefined; }
function formatSize(size: number) { return size < 1024*1024 ? `${Math.max(1, Math.round(size/1024))} KB` : `${(size/1024/1024).toFixed(1)} MB`; }

export default function FilesPage() {
  const { setHeaderTitle, setHeaderActions } = useLayoutHeaderActions();
  const navigate = useNavigate();
  const authMode = useAuthStore((state) => state.authMode);
  const [items, setItems] = useState<Awaited<ReturnType<typeof api.listFiles>>['items']>([]);
  const [allItems, setAllItems] = useState<Awaited<ReturnType<typeof api.listFiles>>['items']>([]);
  const [category, setCategory] = useState<Category>('all'); const [range, setRange] = useState('all'); const [selected, setSelected] = useState<string[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [selectionMode, setSelectionMode] = useState(false);
  const [activeIndex, setActiveIndex] = useState<number | null>(null);
  const [previewText, setPreviewText] = useState('');
  const audioRef = useRef<HTMLAudioElement | null>(null);
  const selectionAnchor = useRef<number | null>(null);
  const isUnreferenced = range === 'unreferenced';
  const isCloudOnly = range === 'cloud-only';
  const specialCategory = specialCategories.has(range) ? range : undefined;
  const load = useCallback(async () => { setLoading(true); setError(''); const localItems = Object.values(useMessageStore.getState().messages).flatMap((message) => ((message as { metadata?: { attachments?: Array<{ id: string; assetId?: string; kind: string; url?: string; mimeType?: string; sizeBytes?: number; createdAt?: number; altText?: string; caption?: string; promptText?: string }> } }).metadata?.attachments || []).filter((attachment) => attachment.url).map((attachment) => ({ id: attachment.assetId || `local-${message.id}-${attachment.id}`, name: attachment.kind === 'audio' ? '语音' : attachment.kind === 'sticker' ? '表情' : '图片', url: attachment.url || '', mimeType: attachment.mimeType || '', sizeBytes: attachment.sizeBytes || 0, kind: attachment.kind, category: attachment.kind === 'audio' ? 'audio' : attachment.kind === 'sticker' ? 'sticker' : 'image', createdAt: attachment.createdAt || message.timestamp, deletedAt: null, chatId: message.chatId, messageId: message.id, description: attachment.caption || attachment.altText, promptText: attachment.promptText, syncStatus: 'local-only' as const }))); setAllItems(localItems); setItems(localItems); setSelected([]); if (authMode !== 'cloud') { setLoading(false); return; } try { const result = await api.listFiles({ trash: isUnreferenced ? 'unreferenced' : false, category: specialCategory, from: isUnreferenced ? undefined : rangeStart(range), limit: 40, offset: 0 }); const localById = new Map(localItems.map((item) => [item.id, item])); const cloudItems = result.items.map((item) => localById.has(item.id) ? { ...item, url: localById.get(item.id)?.url || item.url, syncStatus: 'synced' as const } : item); const cloudIds = new Set(cloudItems.map((item) => item.id)); const merged = isUnreferenced || isCloudOnly ? cloudItems : [...localItems.filter((item) => !cloudIds.has(item.id)), ...cloudItems]; setAllItems(isCloudOnly ? cloudItems.filter((item) => item.syncStatus === 'cloud-only') : merged); } catch (e) { setError(e instanceof Error ? e.message : '云端文件暂时无法加载，本地文件仍可用'); } finally { setLoading(false); } }, [authMode, isUnreferenced, isCloudOnly, specialCategory, range]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { const activeCategory = specialCategory || category; setItems(activeCategory === 'all' ? allItems : allItems.filter((item) => item.category === activeCategory)); }, [allItems, category, specialCategory]);
  const activeItem = activeIndex == null ? null : items[activeIndex];
  useEffect(() => { let cancelled = false; setPreviewText(''); if (!activeItem || !activeItem.url || activeItem.category === 'image' || activeItem.category === 'audio' || activeItem.sizeBytes > 1024 * 1024 || activeItem.mimeType.includes('html')) return undefined; void fetch(activeItem.url).then((response) => response.text()).then((text) => { if (!cancelled) setPreviewText(text.slice(0, 200000)); }).catch(() => undefined); return () => { cancelled = true; }; }, [activeItem]);
  const toggle = (id: string) => setSelected((current) => { const index = items.findIndex((item) => item.id === id); if (index >= 0) selectionAnchor.current = index; return current.includes(id) ? current.filter((item) => item !== id) : [...current, id]; });
  const selectRange = (index: number) => { const anchor = selectionAnchor.current ?? index; const lo = Math.max(0, Math.min(anchor, index)); const hi = Math.min(items.length - 1, Math.max(anchor, index)); const ids = items.slice(lo, hi + 1).map((item) => item.id); setSelected((current) => { const allSelected = ids.every((id) => current.includes(id)); return allSelected ? current.filter((id) => !ids.includes(id)) : Array.from(new Set([...current, ...ids])); }); selectionAnchor.current = index; };
  const doDelete = useCallback(async () => { if (!selected.length) return; try { await api.deleteFiles(selected); await load(); } catch (e) { setError(e instanceof Error ? e.message : '文件删除失败'); } }, [selected, load]);
  const multiSelect = selected.length > 0 || selectionMode;
  const categoryCounts = allItems.reduce<Record<string, number>>((counts, item) => { counts[item.category] = (counts[item.category] || 0) + 1; return counts; }, {});
  const visibleCategories = categories.filter(([value]) => value === 'all' || (categoryCounts[value] || 0) > 0);
  useEffect(() => { setHeaderTitle('文件'); setHeaderActions(multiSelect ? <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}><Typography variant="body2" color="text.secondary">{selected.length} 项 · {formatSize(items.filter((item) => selected.includes(item.id)).reduce((sum, item) => sum + item.sizeBytes, 0))}</Typography><IconButton size="small" onClick={() => { setSelectionMode(false); setSelected([]); }}><CloseIcon /></IconButton><IconButton color="error" disabled={!selected.length} onClick={() => void doDelete()}><DeleteOutlineIcon /></IconButton></Box> : null); return () => { setHeaderTitle(null); setHeaderActions(null); }; }, [setHeaderActions, setHeaderTitle, multiSelect, selected, items, doDelete]);
  const pressTimer = useRef<number | null>(null);
  const beginPress = (id: string) => { pressTimer.current = window.setTimeout(() => { if (!selectionMode) { setSelectionMode(true); toggle(id); } else selectRange(items.findIndex((item) => item.id === id)); }, 520); };
  const endPress = () => { if (pressTimer.current !== null) { window.clearTimeout(pressTimer.current); pressTimer.current = null; } };
  return <Box sx={{ maxWidth: 1160, mx: 'auto', p: { xs: 2, md: 4 }, pb: 8 }}>
    <Box sx={{ display: 'flex', gap: .7, alignItems: 'center', mb: 2, flexWrap: 'wrap' }}><Box sx={{ display: 'flex', gap: .7, flexWrap: 'wrap', flex: 1 }}>{visibleCategories.map(([value, label]) => <Chip key={value} label={`${label}${value === 'all' ? '' : ` ${categoryCounts[value] || 0}`}`} onClick={() => setCategory(value)} color={category === value ? 'primary' : 'default'} variant={category === value ? 'filled' : 'outlined'} />)}</Box><FormControl size="small" sx={{ minWidth: 120, ml: 'auto' }}><InputLabel>筛选</InputLabel><Select value={range} label="筛选" onChange={(e) => setRange(e.target.value)}>{ranges.map(([value, label], index) => <MenuItem key={value} value={value} sx={{ position: 'relative' }}>{(index === 5 || index === ranges.length - 1) && <Divider sx={{ position: 'absolute', left: 0, right: 0, top: 0 }} />}{label}</MenuItem>)}</Select></FormControl></Box>
    {error && <Alert severity="error" sx={{ mb: 2 }} onClose={() => setError('')}>{error}</Alert>}
    {loading ? <Box sx={{ display: 'grid', placeItems: 'center', minHeight: 240 }}><CircularProgress /></Box> : items.length === 0 ? <Card sx={{ borderRadius: 3, p: 5, textAlign: 'center' }}><Typography variant="h6">这里还没有文件</Typography><Typography color="text.secondary" sx={{ mt: 1 }}>{isUnreferenced ? '没有待处理的悬空文件。' : '当 AI 生成图片或语音后，它们会出现在这里。'}</Typography></Card> : <Box sx={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill,minmax(180px,1fr))', gap: 1.5 }}>{items.map((item, index) => <Card key={item.id} onClick={() => { if (!selectionMode) setActiveIndex(index); }} onContextMenu={(e) => { e.preventDefault(); if (selectionMode) selectRange(index); else { setSelectionMode(true); toggle(item.id); } }} onPointerDown={() => beginPress(item.id)} onPointerUp={endPress} onPointerLeave={endPress} sx={{ position: 'relative', borderRadius: 2.5, cursor: item.url ? 'pointer' : 'default', transition: 'transform .2s, box-shadow .2s', '&:hover': { transform: 'translateY(-3px)', boxShadow: 6 } }}><CardContent sx={{ p: 1.5 }}>{selectionMode && <Checkbox size="small" checked={selected.includes(item.id)} onChange={() => toggle(item.id)} onClick={(e) => e.stopPropagation()} sx={{ position: 'absolute', top: 6, left: 6, zIndex: 1, p: .2 }} />}<Box sx={{ width: '100%', height: 86, display: 'grid', placeItems: 'center', overflow: 'hidden', borderRadius: 1.5, bgcolor: 'action.hover', color: 'primary.main' }}>{item.category === 'image' && item.url ? <Box component="img" src={item.url} alt={item.name} sx={{ width: '100%', height: '100%', objectFit: 'cover' }} /> : item.category === 'audio' ? <audio src={item.url} controls onClick={(e) => e.stopPropagation()} style={{ width: '100%' }} /> : icon(item.category)}</Box><Typography noWrap sx={{ mt: 1, fontWeight: 750 }}>{item.name}</Typography>{item.description && <Typography variant="caption" color="text.secondary" sx={{ display: "block" }} noWrap>{item.description}</Typography>}<Typography variant="caption" color="text.secondary">{formatSize(item.sizeBytes)} · {new Date(item.createdAt).toLocaleDateString()}</Typography></CardContent></Card>)}</Box>}
    <Dialog open={activeItem !== null} onClose={() => setActiveIndex(null)} maxWidth="md" fullWidth><DialogContent sx={{ p: 1.5, minHeight: 320, position: 'relative' }}>{activeItem && <><IconButton onClick={() => setActiveIndex((index) => index == null ? null : (index - 1 + items.length) % items.length)} sx={{ position: 'absolute', left: 8, top: '50%', zIndex: 2 }}><ChevronLeftIcon /></IconButton><IconButton onClick={() => setActiveIndex((index) => index == null ? null : (index + 1) % items.length)} sx={{ position: 'absolute', right: 8, top: '50%', zIndex: 2 }}><ChevronRightIcon /></IconButton><Box sx={{ px: 5, py: 2 }}>{activeItem.characterName && <Typography variant="caption" color="text.secondary" sx={{ display: "block", mb: 1, cursor: "pointer" }} onClick={() => navigate(`/characters/${activeItem.characterId}/edit`)}>角色：{activeItem.characterName} · 查看角色</Typography>}{activeItem.promptText && <Typography variant="body2" color="text.secondary" sx={{ mb: 1 }}>提示词：{activeItem.promptText}</Typography>}{activeItem.description && <Typography variant="body2" sx={{ mb: 1 }}>{activeItem.description}</Typography>}{activeItem.category === 'image' ? <Box component="img" src={activeItem.url} alt={activeItem.name} sx={{ display: 'block', maxWidth: '100%', maxHeight: '70vh', mx: 'auto', objectFit: 'contain' }} /> : activeItem.category === 'audio' ? <Box sx={{ display: 'grid', placeItems: 'center', minHeight: 220 }}><audio ref={audioRef} src={activeItem.url} controls autoPlay style={{ width: '100%' }} /></Box> : activeItem.mimeType.includes('html') ? <Box component="iframe" src={activeItem.url} title={activeItem.name} sandbox="allow-scripts" sx={{ width: '100%', height: '65vh', border: 0 }} /> : <Box component="pre" sx={{ whiteSpace: 'pre-wrap', wordBreak: 'break-word', maxHeight: '65vh', overflow: 'auto', m: 0, fontFamily: 'inherit' }}>{previewText || '正在加载预览…'}</Box>}</Box></>}</DialogContent></Dialog>
  </Box>;
}
